window.env = {
  "ALLUSERSPROFILE": "C:\\ProgramData",
  "APPDATA": "C:\\Users\\Mikhail\\AppData\\Roaming",
  "ChocolateyInstall": "C:\\ProgramData\\chocolatey",
  "ChocolateyLastPathUpdate": "132726190663046841",
  "CHROME_CRASHPAD_PIPE_NAME": "\\\\.\\pipe\\crashpad_16992_LITDRWPNAQYZQTZO",
  "COLOR": "1",
  "COLORTERM": "truecolor",
  "CommonProgramFiles": "C:\\Program Files\\Common Files",
  "CommonProgramFiles(x86)": "C:\\Program Files (x86)\\Common Files",
  "CommonProgramW6432": "C:\\Program Files\\Common Files",
  "COMPUTERNAME": "DESKTOP-NPCTU89",
  "ComSpec": "C:\\Windows\\system32\\cmd.exe",
  "DriverData": "C:\\Windows\\System32\\Drivers\\DriverData",
  "EDITOR": "notepad.exe",
  "FPS_BROWSER_APP_PROFILE_STRING": "Internet Explorer",
  "FPS_BROWSER_USER_PROFILE_STRING": "Default",
  "GIT_ASKPASS": "c:\\Users\\Mikhail\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass.sh",
  "GOOGLE_API_KEY": "AIzaSyDKQKeCVLB5j1ZAow4QN4r26LhyUZOgKK8",
  "HOME": "C:\\Users\\Mikhail",
  "HOMEDRIVE": "C:",
  "HOMEPATH": "\\Users\\Mikhail",
  "INIT_CWD": "M:\\WEB\\EKO\\EKO_GOOGLE_MAP",
  "LANG": "ru_RU.UTF-8",
  "LOCALAPPDATA": "C:\\Users\\Mikhail\\AppData\\Local",
  "LOGONSERVER": "\\\\DESKTOP-NPCTU89",
  "NODE": "C:\\Program Files\\nodejs\\node.exe",
  "NODE_EXE": "C:\\Program Files\\nodejs\\\\node.exe",
  "NPM_CLI_JS": "C:\\Program Files\\nodejs\\\\node_modules\\npm\\bin\\npm-cli.js",
  "npm_command": "start",
  "npm_config_cache": "C:\\Users\\Mikhail\\AppData\\Local\\npm-cache",
  "npm_config_globalconfig": "C:\\Users\\Mikhail\\AppData\\Roaming\\npm\\etc\\npmrc",
  "npm_config_global_prefix": "C:\\Users\\Mikhail\\AppData\\Roaming\\npm",
  "npm_config_init_module": "C:\\Users\\Mikhail\\.npm-init.js",
  "npm_config_local_prefix": "M:\\WEB\\EKO\\EKO_GOOGLE_MAP",
  "npm_config_metrics_registry": "https://registry.npmjs.org/",
  "npm_config_node_gyp": "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js",
  "npm_config_noproxy": "",
  "npm_config_prefix": "C:\\Users\\Mikhail\\AppData\\Roaming\\npm",
  "npm_config_userconfig": "C:\\Users\\Mikhail\\.npmrc",
  "npm_config_user_agent": "npm/8.1.0 node/v17.0.1 win32 x64 workspaces/false",
  "npm_execpath": "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js",
  "npm_lifecycle_event": "start",
  "npm_lifecycle_script": "react-dotenv && react-scripts --openssl-legacy-provider start",
  "npm_node_execpath": "C:\\Program Files\\nodejs\\node.exe",
  "npm_package_json": "M:\\WEB\\EKO\\EKO_GOOGLE_MAP\\package.json",
  "npm_package_name": "ecogooglemap",
  "npm_package_version": "0.1.0",
  "NPM_PREFIX_NPM_CLI_JS": "C:\\Users\\Mikhail\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js",
  "NUMBER_OF_PROCESSORS": "8",
  "OneDrive": "C:\\Users\\Mikhail\\OneDrive",
  "ORIGINAL_XDG_CURRENT_DESKTOP": "undefined",
  "OS": "Windows_NT",
  "Path": "M:\\WEB\\EKO\\EKO_GOOGLE_MAP\\node_modules\\.bin;M:\\WEB\\EKO\\node_modules\\.bin;M:\\WEB\\node_modules\\.bin;M:\\node_modules\\.bin;C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\@npmcli\\run-script\\lib\\node-gyp-bin;C:\\Python39\\Scripts\\;C:\\Python39\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\dotnet\\;C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\170\\Tools\\Binn\\;C:\\Program Files\\MATLAB\\R2015b\\runtime\\win64;C:\\Program Files\\MATLAB\\R2015b\\bin;C:\\Program Files\\MATLAB\\R2015b\\polyspace\\bin;C:\\Program Files\\TortoiseGit\\bin;;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files\\nodejs\\;C:\\Users\\Mikhail\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\Mikhail\\.dotnet\\tools;C:\\Users\\Mikhail\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\Mikhail\\.dotnet\\tools;C:\\Users\\Mikhail\\AppData\\Local\\GitHubDesktop\\bin;C:\\Users\\Mikhail\\AppData\\Roaming\\npm",
  "PATHEXT": ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW;.CPL",
  "PROCESSOR_ARCHITECTURE": "AMD64",
  "PROCESSOR_IDENTIFIER": "AMD64 Family 23 Model 24 Stepping 1, AuthenticAMD",
  "PROCESSOR_LEVEL": "23",
  "PROCESSOR_REVISION": "1801",
  "ProgramData": "C:\\ProgramData",
  "ProgramFiles": "C:\\Program Files",
  "ProgramFiles(x86)": "C:\\Program Files (x86)",
  "ProgramW6432": "C:\\Program Files",
  "PROMPT": "$P$G",
  "PSModulePath": "C:\\Users\\Mikhail\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules",
  "PUBLIC": "C:\\Users\\Public",
  "SESSIONNAME": "Console",
  "SystemDrive": "C:",
  "SystemRoot": "C:\\Windows",
  "TEMP": "C:\\Users\\Mikhail\\AppData\\Local\\Temp",
  "TERM_PROGRAM": "vscode",
  "TERM_PROGRAM_VERSION": "1.62.3",
  "TMP": "C:\\Users\\Mikhail\\AppData\\Local\\Temp",
  "USERDOMAIN": "DESKTOP-NPCTU89",
  "USERDOMAIN_ROAMINGPROFILE": "DESKTOP-NPCTU89",
  "USERNAME": "Mikhail",
  "USERPROFILE": "C:\\Users\\Mikhail",
  "VSCODE_GIT_ASKPASS_EXTRA_ARGS": "--ms-enable-electron-run-as-node",
  "VSCODE_GIT_ASKPASS_MAIN": "c:\\Users\\Mikhail\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass-main.js",
  "VSCODE_GIT_ASKPASS_NODE": "C:\\Users\\Mikhail\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe",
  "VSCODE_GIT_IPC_HANDLE": "\\\\.\\pipe\\vscode-git-db9002eeaf-sock",
  "windir": "C:\\Windows"
};